arb-dir: lib/core/bahasa
template-arb-file: app_id.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/core/bahasa
preferred-supported-locales:
  - id
  - en
nullable-getter: false
